name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  basic:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            install-gtest-command: 'Invoke-Expression "$env:VCPKG_INSTALLATION_ROOT\vcpkg install GTest:x64-windows"'
            vcpkg-toolchain: "$env:VCPKG_INSTALLATION_ROOT\\scripts\\buildsystems\\vcpkg.cmake"
          - os: ubuntu-latest
            install-gtest-command: "$VCPKG_INSTALLATION_ROOT/vcpkg install GTest"
            vcpkg-toolchain: "$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"
          - os: macos-latest
            install-gtest-command: "$VCPKG_INSTALLATION_ROOT/vcpkg install GTest"
            vcpkg-toolchain: "$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"

    steps:
    - uses: actions/checkout@v3
    
    - name: Install GTest
      run: ${{matrix.install-gtest-command}}

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE="${{matrix.vcpkg-toolchain}}"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
      
